### ISSUE TITLE
My code stuck at evaluating nuscenes test set detection 

### ISSUE THREAD

**Issue by mincheoree** [Cloud-CV/EvalAI#4158]
_Thanks for taking the time to report a bug in the EvalAI project, or propose a new feature! Before creating a new issue, please do a quick search to check that it hasn't already been filed on the [issue tracker](https://github.com/Cloud-CV/EvalAI/issues)._

If you'd like to report a bug, please include the following information:
- the expected behaviour
- the observed behaviour
- steps to reproduce the problem
- which operating system and/or browser you're using, if relevant
- (if possible) copies of the console/server logs

On the other hand, if you'd like to propose a new feature:
- please describe, as clearly as possible, what you'd like to see
- (if possible) include mockups/screenshots, if these would help convey the meaning better

Thanks!

![image](https://github.com/Cloud-CV/EvalAI/assets/65105015/ea73b066-982d-40ce-81c3-67cd11448312)

**Comment by mincheoree** [comment]
Hello @Ram81 @David_Novotny @Rishabh_Jain @rishabh @gchhablani, 
I am really sorry to bother you, but my nuscenes test set submission stays at 'Submitted' status for 3 days from September 1st. May I ask if there is problem in the server? Thanks for hard work!

**Comment by gchhablani** [comment]
@mincheoree This is fixed. Please let us know in case of issues. Thanks!

**Comment by mincheoree** [comment]
@gchhablani but mine still hangs at 'Submitted' even I resubmitted results.json. From my previous experience, isn't it supposed to turn into 'Processing' status in few minutes?
![image](https://github.com/Cloud-CV/EvalAI/assets/65105015/d53bbecb-3877-4d0f-9d68-2fede9eda69d)
