### ISSUE TITLE
Wrong message coming on Signup Page.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#575]
Follow these steps:
1. login with wrong crdentials.
2. Then move to signup page.
then there is a message at bottom of Signup form saying "Unable to log in with provided credentials."

Need to remove or empty that msg variable.

**Comment by anweshknayak** [comment]
I can do this ?

**Comment by aka-jain** [comment]
Sure, assiging it to you @anweshknayak .

**Comment by anweshknayak** [comment]
Oops I can't test it.(blank screen) I forgot.  I have to search through the code.

**Comment by aka-jain** [comment]
@anweshknayak Is error persist at clientside or backened side. If it is client then can you please share the snapshot of console?

**Comment by spyshiv** [comment]
@aka-jain : We need to refresh controller on route change. Since both signup and login share same controller (AuthCtrl) and same variables (vm.isFormError, vm.FormError) that's why this is happening.

**Comment by aka-jain** [comment]
@spyshiv Or we can make that msg variable empty on clicking signup tab. Thoughts?

**Comment by spyshiv** [comment]
:+1: that's better solution since this issue is not related to ng-messages.
@anweshknayak : Do it as @aka-jain suggested. (Resetting the variables)

**Comment by yadavankit** [comment]
am emptying the auth.FormError var on ng-click SignUp in signup.html, I guess this should do the trick, but no change in signup.html is being reflected on browser. Am I missing something?

**Comment by aka-jain** [comment]
@yadavankit Can you put up a PR for this?

**Comment by anweshknayak** [comment]
#592 @aka-jain There were some issue I guess

**Comment by aka-jain** [comment]
I have already mentioned that we have to do some changes. And I was in doudt regarding your code as some enhancement to quality needs to be done. That's why I closed that issue.

**Comment by yadavankit** [comment]
@aka-jain yeah sure 👍

**Comment by yadavankit** [comment]
#633 @aka-jain

**Comment by anweshknayak** [comment]
@yadavankit make sure if anyone has been assigned beforehand before picking up the issue. Effort goes into waste of either one.

**Comment by aka-jain** [comment]
Fixed with #636

**Comment by anweshknayak** [comment]
@aka-jain error still persists. 
Go to : Login . 
Next Click below : SignUp 
Form error shows up. 

Please check the PR. #663

**Comment by anweshknayak** [comment]
@yadavankit there's no need. a functionality has been added in #632 which will do.

**Comment by yadavankit** [comment]
@anweshknayak cool 👍
